# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who_to_greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  hardcoded1:
    value: "hardcoded1-value"
  hardcoded2:
    value: "hardcoded2-value"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
    - "secondarg"